version: "3.5"

services:
  frontend:
    build:
      context: ../
      dockerfile: deploy/Dockerfile

    image: frontend:latest

    container_name: frontend

    networks:
      - frontend

    ports:
      - "8080:80"

    volumes:
      - ./conf:/etc/nginx/conf.d
#      - ./html:/srv/http/

networks:
  frontend:
